@startuml

|Student|
start
:Open registration form;

repeat 
    :Enter registration data;
    :Send registration data;
    :Registration data;
    |System|
    :Validate data;
backward:Show validation error;
repeat while () is (Data isn't valid)
->Data is valid;

:Check if students exists;

if () then (Student doesn't exist)
    :Create account;
        fork
            :Send confirmation message;
            :Confirmation message;
            |Student|
            :Close registration form;
            stop
        fork again
            |System|
            :Save student data in DB;
        end merge
        stop
else (Student exists)
:Show error;
stop

@enduml